apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap-app.yaml
  - pgbouncer.yaml
  - server-api.yaml
  - server-auth.yaml
  - server-worker.yaml
  - assistant-service.yaml
  - web.yaml
  - hpa.yaml
  - pdb.yaml
  - ingress.yaml
